### ISSUE TITLE
Return vnet network id from data source/ vnet resource output

### ISSUE THREAD

**Issue by bashinate-trustgrid-1982** [trustgrid/terraform-provider-tg#32]
needed for any resource that requires the vnet id 

example vnet tunnel interface:
`tunnel {
    name       = "vnet1"
    network_id = 1125
    vrf        = "vpn"
    type       = "vnet"
    enabled    = true
    mtu        = 1430
  }`

**Comment by terrbear** [comment]
done in 1.0.0
